# Generated by Django 5.2.16 on 2026-08-04 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Mới mở"),
                            ("REVIEWING", "Đang xem xét"),
                            ("RESOLVED", "Đã giải quyết"),
                            ("CLOSED", "Đã đóng"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REFUND_FULL", "Hoàn toàn bộ"),
                            ("REFUND_PARTIAL", "Hoàn một phần"),
                            ("REJECT", "Từ chối"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=18, null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="order.shoporder",
                    ),
                ),
            ],
            options={
                "db_table": "disputes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="after_sales.dispute",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispute_evidence",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Đã yêu cầu"),
                            ("SELLER_APPROVED", "Seller đồng ý"),
                            ("SELLER_REJECTED", "Seller từ chối"),
                            ("RETURNING", "Đang trả hàng"),
                            ("RECEIVED", "Đã nhận hàng trả"),
                            ("REFUND_PENDING", "Chờ hoàn tiền"),
                            ("REFUNDED", "Đã hoàn tiền"),
                            ("ESCALATED", "Đã khiếu nại"),
                            ("CLOSED", "Đã đóng"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                ("reason_code", models.CharField(max_length=50)),
                ("reason_detail", models.TextField()),
                ("seller_response", models.TextField(blank=True)),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="order.shoporder",
                    ),
                ),
            ],
            options={
                "db_table": "return_requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="dispute",
            name="return_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispute",
                to="after_sales.returnrequest",
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "requested_refund_amount",
                    models.DecimalField(decimal_places=0, max_digits=18),
                ),
                (
                    "approved_refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_request_items",
                        to="order.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="after_sales.returnrequest",
                    ),
                ),
            ],
            options={
                "db_table": "return_request_items",
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(max_length=1000)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Ảnh"), ("VIDEO", "Video")], max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="after_sales.returnrequest",
                    ),
                ),
            ],
            options={
                "db_table": "return_request_media",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["shop_order", "status"], name="return_shop_order_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["customer", "-requested_at"],
                name="return_customer_requested_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "-created_at"], name="dispute_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.UniqueConstraint(
                fields=("return_request", "order_item"), name="return_request_item_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="return_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_refund_amount__gte", 0)),
                name="return_item_requested_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_refund_amount__isnull", True),
                    ("approved_refund_amount__gte", 0),
                    _connector="OR",
                ),
                name="return_item_approved_nonnegative",
            ),
        ),
    ]
