# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_notification_kind'),
        ('product', '0004_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='account.customerprofile')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('is_selected', models.BooleanField(default=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='product.productvariant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['cart', 'is_selected'], name='cart_item_selected_idx')],
                'constraints': [models.UniqueConstraint(fields=('cart', 'variant'), name='cart_item_cart_variant_uniq'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 0)), name='cart_item_snapshot_nonnegative')],
            },
        ),
    ]
