# Generated by Django 5.2.16 on 2026-07-28 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_inventory_balances(apps, schema_editor):
    ProductVariant = apps.get_model("product", "ProductVariant")
    InventoryBalance = apps.get_model("inventory", "InventoryBalance")
    InventoryBalance.objects.bulk_create(
        [
            InventoryBalance(
                variant_id=variant.pk,
                available_stock=variant.stock_quantity,
                reserved_stock=0,
            )
            for variant in ProductVariant.objects.all().iterator(chunk_size=500)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_notification_kind'),
        ('product', '0003_normalize_null_variant_barcodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('confirmed', 'Đã xác nhận')], db_index=True, default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='account.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=18)),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_items', to='product.productvariant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho'), ('adjustment', 'Điều chỉnh'), ('reserve', 'Giữ kho'), ('release', 'Hoàn giữ kho'), ('commit', 'Chốt bán')], db_index=True, max_length=20)),
                ('bucket', models.CharField(choices=[('available', 'Khả dụng'), ('reserved', 'Đã giữ')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reference_type', models.CharField(choices=[('stock_entry', 'Phiếu nhập'), ('stock_out', 'Phiếu xuất'), ('adjustment', 'Kiểm kê'), ('order', 'Đơn hàng')], max_length=20)),
                ('reference_id', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='product.productvariant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockOutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('out', 'Xuất kho'), ('adjustment', 'Kiểm kê')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('confirmed', 'Đã xác nhận')], db_index=True, default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_stock_out_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_out_entries', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_entries', to='account.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockOutEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('stock_out_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockoutentry')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_entry_items', to='product.productvariant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_reference', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Đang giữ'), ('released', 'Đã hoàn'), ('committed', 'Đã chốt'), ('expired', 'Hết hạn')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='product.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_stock', models.IntegerField(default=0)),
                ('reserved_stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balance', to='product.productvariant')),
            ],
            options={
                'ordering': ('variant__sku',),
                'indexes': [models.Index(fields=['created_at'], name='inventory_balance_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_stock__gte', 0)), name='inventory_available_nonnegative'), models.CheckConstraint(condition=models.Q(('reserved_stock__gte', 0)), name='inventory_reserved_nonnegative'), models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='inventory_threshold_nonnegative')],
            },
        ),
        migrations.RunPython(
            backfill_inventory_balances,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_notified', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='product.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['variant', 'is_notified'], name='stock_alert_variant_idx'), models.Index(fields=['created_at'], name='stock_alert_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('variant', 'user'), name='stock_alert_variant_user_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['shop', 'status'], name='stock_entry_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['created_at'], name='stock_entry_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('status', 'confirmed')), _connector='OR'), name='stock_entry_confirmation_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_entry_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_entry_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockentryitem',
            constraint=models.UniqueConstraint(fields=('stock_entry', 'variant'), name='stock_entry_variant_unique'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', '-created_at'], name='stock_move_variant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_move_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_move_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='stock_movement_balance_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stockoutentry',
            index=models.Index(fields=['shop', 'status'], name='stock_out_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoutentry',
            index=models.Index(fields=['created_at'], name='stock_out_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockoutentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('status', 'confirmed')), _connector='OR'), name='stock_out_confirmation_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockoutentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_out_item_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockoutentryitem',
            constraint=models.UniqueConstraint(fields=('stock_out_entry', 'variant'), name='stock_out_entry_variant_unique'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_reference', 'status'], name='stock_res_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='stock_reservation_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['created_at'], name='stock_reservation_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(fields=('variant', 'order_reference'), name='stock_reservation_variant_order_unique'),
        ),
    ]
