# Generated by Django 5.2.16 on 2026-07-27 04:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_shop_cover_shop_logo'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('display_type', models.CharField(choices=[('text', 'Văn bản'), ('color', 'Màu sắc'), ('image', 'Hình ảnh')], default='text', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='account.shop')),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=120)),
                ('display_value', models.CharField(blank=True, max_length=120, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.attribute')),
            ],
            options={
                'ordering': ('sort_order', 'value', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(db_index=False, max_length=280)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('pending_review', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('hidden', 'Đã ẩn'), ('suspended', 'Tạm ngưng')], db_index=True, default='draft', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('sold_count', models.PositiveBigIntegerField(default=0)),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='product.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_links', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(related_name='products', through='product.ProductAttributeValue', to='product.attributevalue'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='account.shop')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], default='image', max_length=20)),
                ('file_url', models.TextField()),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='product.productvariant')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='product.attribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='product.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_links', to='product.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', through='product.VariantAttributeValue', to='product.attributevalue'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'name'), name='attribute_shop_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('name',), name='attribute_global_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'code'), name='attribute_shop_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('code',), name='attribute_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='attribute_value_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_value'), name='product_attribute_value_uniq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['status', '-created_at'], name='ix_products_public_feed'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='product_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('shop', 'slug'), name='product_shop_slug_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('min_price__gte', 0), _connector='OR'), name='product_min_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('max_price__isnull', True), ('max_price__gte', 0), _connector='OR'), name='product_max_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('min_price__lte', models.F('max_price')), _connector='OR'), name='product_price_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('rating_average__gte', 0), ('rating_average__lte', 5)), name='product_rating_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='product_primary_media_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='variant_attribute_uniq'),
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='variant_attribute_value_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('shop', 'sku'), name='variant_shop_sku_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('shop', 'barcode'), name='variant_shop_barcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('original_price__gte', 0)), name='variant_original_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='variant_sale_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='variant_cost_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__isnull', True), ('weight_grams__gt', 0), _connector='OR'), name='variant_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('original_price', 0), ('sale_price__lte', models.F('original_price')), _connector='OR'), name='variant_sale_not_above_original'),
        ),
    ]
