# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
