# Generated by Django 5.2.16 on 2026-07-24 02:20

import apps.account.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_and_user_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('seller_application', 'Hồ sơ seller'), ('document_review', 'Xác minh giấy tờ'), ('shop_status', 'Trạng thái gian hàng')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('id_card', 'CCCD/CMND'), ('business_license', 'Giấy phép kinh doanh'), ('tax_registration', 'Đăng ký thuế'), ('other', 'Khác')], db_index=True, max_length=30)),
                ('file', models.FileField(upload_to=apps.account.models.seller_document_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Chờ xác minh'), ('verified', 'Đã xác minh'), ('additional_required', 'Yêu cầu bổ sung')], db_index=True, default='pending', max_length=30)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('document_type', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('locked', 'Bị khóa')], db_index=True, default='approved', max_length=20)),
                ('lock_reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ('-submitted_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm 9-15 chữ số và có thể bắt đầu bằng dấu +', regex='^\\+?[0-9]{9,15}$')]),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Chưa xác minh'), ('pending', 'Chờ xác minh'), ('verified', 'Đã xác minh')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['onboarding_status', 'created_at'], name='seller_status_created_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdocument',
            name='seller_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.sellerprofile'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notif_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocument',
            index=models.Index(fields=['seller_profile', 'is_deleted'], name='seller_doc_profile_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status', 'is_deleted'], name='shop_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='shop_created_idx'),
        ),
    ]
