# Generated by Django 5.2.16 on 2026-07-24 03:42

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification_sellerdocument_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, upload_to=apps.account.models.shop_cover_upload_to),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.account.models.shop_logo_upload_to),
        ),
    ]
