# Generated by Django 5.2.16 on 2026-07-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_use_urls_for_shop_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('seller_application', 'Hồ sơ seller'), ('document_review', 'Xác minh giấy tờ'), ('shop_status', 'Trạng thái gian hàng'), ('inventory_low_stock', 'Tồn kho thấp'), ('back_in_stock', 'Có hàng trở lại')], db_index=True, max_length=30),
        ),
    ]
