# Generated by Django 5.2.16 on 2026-08-03 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('method', models.CharField(max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thất bại'), ('EXPIRED', 'Hết hạn'), ('CANCELLED', 'Đã hủy'), ('REFUND_PENDING', 'Chờ hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền')], db_index=True, default='PENDING', max_length=30)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=30)),
                ('provider_event_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(null=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Đã nhận'), ('PROCESSED', 'Đã xử lý'), ('IGNORED_DUPLICATE', 'Bỏ qua do trùng'), ('FAILED', 'Thất bại')], default='RECEIVED', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.payment')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_request_id', models.UUIDField(blank=True, null=True)),
                ('refund_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('SUCCEEDED', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payment.payment')),
                ('shop_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='order.shoporder')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
