# Generated by Django 5.2.16 on 2026-08-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("after_sales", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refund",
            name="return_request_id",
        ),
        migrations.AddField(
            model_name="refund",
            name="return_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="after_sales.returnrequest",
            ),
        ),
    ]
