# Generated by Django 5.2.16 on 2026-07-29 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('image_url', models.TextField()),
                ('target_url', models.TextField(blank=True)),
                ('position', models.CharField(choices=[('hero', 'Hero'), ('middle', 'Giữa trang')], db_index=True, default='hero', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('position', 'sort_order', 'created_at', 'id'),
                'indexes': [models.Index(fields=['position', 'is_active', 'is_deleted', 'sort_order'], name='banner_public_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='banner_schedule_valid')],
            },
        ),
    ]
