<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { formatCurrency } from '@/shared/lib/formatters'
import { orderApi } from '@/features/order/api'
import type { CommerceOrder } from '@/features/order/types'
const orders=ref<CommerceOrder[]>([]),loading=ref(true),error=ref(''),filters=reactive({status:'',search:'',date_from:'',date_to:''})
async function load(){loading.value=true;try{orders.value=(await orderApi.adminOrders(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)))).data.data}catch{error.value='Không thể tải dữ liệu đơn hàng.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><main class="mx-auto max-w-7xl px-4 py-8"><h1 class="text-3xl font-black">Giám sát đơn hàng</h1><form class="my-5 grid gap-3 rounded-2xl bg-white p-4 md:grid-cols-5" @submit.prevent="load"><input v-model="filters.search" class="rounded-xl border p-3" placeholder="Mã đơn / khách"><select v-model="filters.status" class="rounded-xl border p-3"><option value="">Mọi trạng thái</option><option>PENDING_CONFIRMATION</option><option>CONFIRMED</option><option>SHIPPING</option><option>COMPLETED</option><option>CANCELLED</option></select><input v-model="filters.date_from" type="date" class="rounded-xl border p-3"><input v-model="filters.date_to" type="date" class="rounded-xl border p-3"><button class="rounded-xl bg-slate-950 font-bold text-white">Lọc</button></form><p v-if="loading">Đang tải…</p><p v-else-if="error" class="text-rose-700">{{ error }}</p><div v-else class="overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full text-left"><thead class="bg-slate-100"><tr><th class="p-4">Order</th><th>Payment</th><th>Shop orders</th><th>Tổng</th><th>Ngày đặt</th></tr></thead><tbody><tr v-for="order in orders" :key="order.id" class="border-t"><td class="p-4 font-mono font-bold">{{ order.order_code }}</td><td>{{ order.payment_method }} / {{ order.payment_status }}</td><td><p v-for="shop in order.shop_orders" :key="shop.id">{{ shop.shop_name }}: {{ shop.fulfillment_status }}</p></td><td>{{ formatCurrency(order.grand_total) }}</td><td>{{ new Date(order.placed_at).toLocaleString('vi-VN') }}</td></tr></tbody></table></div></main></template>
