# Generated by Django 5.2.16 on 2026-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auditlog_reason_auditlog_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(max_length=64),
        ),
    ]
