# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_notification_kind'),
        ('catalog', '0001_initial'),
        ('product', '0004_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('start_time', 'id'),
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='flash_sale_window_idx'), models.Index(fields=['is_active', 'start_time', 'end_time'], name='flash_sale_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='flash_sale_valid_time_range')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('platform', 'Sàn'), ('shop', 'Shop')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed_amount', 'Số tiền cố định')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=18)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applicable_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='catalog.category')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='account.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(max_length=64)),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_usages', to='account.customerprofile')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotion.voucher')),
            ],
            options={
                'ordering': ('-used_at',),
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('quota', models.PositiveIntegerField()),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotion.flashsale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_sale_items', to='product.productvariant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('flash_sale', 'variant'), name='flash_sale_item_variant_uniq'), models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='flash_sale_item_price_nonnegative'), models.CheckConstraint(condition=models.Q(('quota__gt', 0)), name='flash_sale_item_quota_positive'), models.CheckConstraint(condition=models.Q(('sold_count__lte', models.F('quota'))), name='flash_sale_item_sold_within_quota')],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_from', 'valid_until'], name='voucher_valid_window_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['scope', 'is_active', 'valid_from', 'valid_until'], name='voucher_active_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'platform'), ('shop__isnull', True)), models.Q(('scope', 'shop'), ('shop__isnull', False)), _connector='OR'), name='voucher_scope_shop_consistent'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='voucher_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gte', 0), _connector='OR'), name='voucher_max_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_amount__gte', 0)), name='voucher_min_order_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit_per_user__gt', 0)), name='voucher_per_user_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__lt', models.F('valid_until'))), name='voucher_valid_time_range'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['voucher', 'user'], name='voucher_usage_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.UniqueConstraint(fields=('voucher', 'user', 'order_reference'), name='voucher_usage_checkout_uniq'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='voucher_usage_discount_nonnegative'),
        ),
    ]
