# Generated by Django 5.2.16 on 2026-08-03 02:12

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_campaign_data(apps, schema_editor):
    Voucher = apps.get_model("promotion", "Voucher")
    VoucherUsage = apps.get_model("promotion", "VoucherUsage")
    for voucher in Voucher.objects.all().iterator():
        old_discount_type = voucher.discount_type
        if old_discount_type == "percentage":
            voucher.discount_type = "percent"
        elif old_discount_type == "fixed_amount":
            voucher.discount_type = "fixed"
        if voucher.total_usage_limit is not None:
            used = VoucherUsage.objects.filter(voucher_id=voucher.pk).count()
            voucher.remaining_quantity = max(0, voucher.total_usage_limit - used)
        voucher.stackable_with = ["shop"] if voucher.scope == "platform" else ["platform"]
        voucher.save(update_fields=("discount_type", "remaining_quantity", "stackable_with"))


def reverse_campaign_data(apps, schema_editor):
    Voucher = apps.get_model("promotion", "Voucher")
    Voucher.objects.filter(discount_type="percent").update(discount_type="percentage")
    Voucher.objects.filter(discount_type="fixed").update(discount_type="fixed_amount")


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_notification_kind"),
        ("catalog", "0001_initial"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVoucher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saved", "Đã lưu"),
                            ("pending_use", "Đang khóa"),
                            ("used", "Đã dùng"),
                            ("expired", "Hết hạn"),
                        ],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("order_id", models.CharField(blank=True, max_length=64, null=True)),
                ("checkout_token", models.UUIDField(blank=True, db_index=True, null=True)),
                ("pending_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "user_voucher",
                "ordering": ("-claimed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="VoucherEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("collect", "Lưu"),
                            ("apply", "Áp dụng"),
                            ("use", "Sử dụng"),
                            ("rollback", "Hoàn tác"),
                            ("expire", "Hết hạn"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="voucher",
            name="applicable_scope",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="collect_type",
            field=models.CharField(
                choices=[("manual", "Người dùng lưu"), ("auto", "Tự động cấp")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="remaining_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="stackable_with",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percent", "Phần trăm"),
                    ("fixed", "Số tiền cố định"),
                    ("freeship", "Miễn phí vận chuyển"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_value",
            field=models.DecimalField(db_column="value", decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="min_order_amount",
            field=models.DecimalField(
                db_column="min_order_value", decimal_places=0, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="scope",
            field=models.CharField(
                choices=[("platform", "Sàn"), ("shop", "Shop")],
                db_column="issuer_type",
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                db_column="issuer_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="account.shop",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="total_usage_limit",
            field=models.PositiveIntegerField(blank=True, db_column="total_quantity", null=True),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="usage_limit_per_user",
            field=models.PositiveIntegerField(db_column="per_user_limit", default=1),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="valid_from",
            field=models.DateTimeField(db_column="start_time"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="valid_until",
            field=models.DateTimeField(db_column="end_time"),
        ),
        migrations.AddConstraint(
            model_name="voucher",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remaining_quantity__isnull", True),
                    ("remaining_quantity__gte", 0),
                    _connector="OR",
                ),
                name="voucher_remaining_nonnegative",
            ),
        ),
        migrations.AlterModelTable(
            name="voucher",
            table="voucher_campaign",
        ),
        migrations.RunPython(migrate_campaign_data, reverse_campaign_data),
        migrations.AddField(
            model_name="uservoucher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_vouchers",
                to="account.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="uservoucher",
            name="voucher_campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_vouchers",
                to="promotion.voucher",
            ),
        ),
        migrations.AddField(
            model_name="voucherevent",
            name="user_voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="promotion.uservoucher",
            ),
        ),
        migrations.AddIndex(
            model_name="uservoucher",
            index=models.Index(
                fields=["user", "status", "voucher_campaign"], name="user_voucher_owner_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="uservoucher",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="user_voucher_collect_idempotent"
            ),
        ),
    ]
