# Generated by Django 5.2.16 on 2026-08-03 04:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_notification_kind'),
        ('product', '0004_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=18)),
                ('platform_discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('shop_discount_total', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('shipping_total', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=0, max_digits=18)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('EXPIRED', 'Hết hạn thanh toán'), ('REFUND_PENDING', 'Chờ hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền')], db_index=True, default='PENDING', max_length=30)),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('VNPAY', 'VNPay')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('checkout_note', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='account.customerprofile')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('province_code', models.CharField(blank=True, max_length=20)),
                ('province_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(blank=True, max_length=20)),
                ('district_name', models.CharField(max_length=100)),
                ('ward_code', models.CharField(blank=True, max_length=20)),
                ('ward_name', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address', to='order.order')),
            ],
            options={
                'db_table': 'order_addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingFeeRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flat_fee', models.DecimalField(decimal_places=0, default=Decimal('30000'), max_digits=18)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_fee_rule', to='account.shop')),
            ],
            options={
                'db_table': 'shipping_fee_rules',
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_order_code', models.CharField(db_index=True, max_length=45, unique=True)),
                ('fulfillment_status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PACKING', 'Đang đóng gói'), ('SHIPPING', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('DELIVERY_FAILED', 'Giao thất bại'), ('RETURN_REQUESTED', 'Yêu cầu trả hàng'), ('RETURNED', 'Đã trả hàng'), ('RETURN_REJECTED', 'Từ chối trả hàng')], db_index=True, default='PENDING_CONFIRMATION', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=18)),
                ('shop_discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('platform_discount_allocated', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('shipping_method_code', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cod_collected_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to='order.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to='account.shop')),
            ],
            options={
                'db_table': 'shop_orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(db_index=True, max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='order.shoporder')),
            ],
            options={
                'db_table': 'order_status_histories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('variant_attributes', models.JSONField(default=dict)),
                ('product_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('unit_original_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('unit_sale_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('quantity', models.PositiveIntegerField()),
                ('line_subtotal', models.DecimalField(decimal_places=0, max_digits=18)),
                ('shop_discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('platform_discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=18)),
                ('cost_price_snapshot', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.product')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.productvariant')),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order.shoporder')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=50)),
                ('reason_detail', models.TextField(blank=True)),
                ('stock_restored_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cancellations', to=settings.AUTH_USER_MODEL)),
                ('shop_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='order.shoporder')),
            ],
            options={
                'db_table': 'order_cancellations',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_customer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('platform_discount__gte', 0)), name='order_platform_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shop_discount_total__gte', 0)), name='order_shop_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_total__gte', 0)), name='order_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='order_grand_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shippingfeerule',
            constraint=models.CheckConstraint(condition=models.Q(('flat_fee__gte', 0)), name='shipping_flat_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shippingfeerule',
            constraint=models.CheckConstraint(condition=models.Q(('free_shipping_threshold__isnull', True), ('free_shipping_threshold__gte', 0), _connector='OR'), name='shipping_free_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['shop', 'fulfillment_status'], name='shop_order_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['fulfillment_status', 'created_at'], name='shop_order_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoporder',
            constraint=models.UniqueConstraint(fields=('order', 'shop'), name='shop_order_order_shop_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shoporder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='shop_order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shoporder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='shop_order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_total_nonnegative'),
        ),
    ]
