# Generated by Django 5.2.16 on 2026-07-29 06:12

import apps.ai.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def create_product_embedding_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    product_embedding = apps.get_model("ai", "ProductEmbedding")
    table = schema_editor.quote_name(product_embedding._meta.db_table)
    column = schema_editor.quote_name(product_embedding._meta.get_field("embedding").column)
    index = schema_editor.quote_name("ai_embed_vector_hnsw")
    schema_editor.execute(
        f"CREATE INDEX IF NOT EXISTS {index} ON {table} "
        f"USING hnsw ({column} vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def drop_product_embedding_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        index = schema_editor.quote_name("ai_embed_vector_hnsw")
        schema_editor.execute(f"DROP INDEX IF EXISTS {index}")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0004_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_vector_extension,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="AIContentCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("feature", models.CharField(db_index=True, max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("language_code", models.CharField(default="vi", max_length=10)),
                (
                    "content_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Content hash must be a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("model_name", models.CharField(max_length=120)),
                ("is_stale", models.BooleanField(db_index=True, default=False)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ("-generated_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["feature", "entity_type", "entity_id"], name="ai_cache_entity_idx"
                    ),
                    models.Index(fields=["is_stale", "expires_at"], name="ai_cache_freshness_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "feature",
                            "entity_type",
                            "entity_id",
                            "language_code",
                            "content_hash",
                        ),
                        name="ai_content_cache_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        default=apps.ai.models.generate_request_id, max_length=100, unique=True
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("smart_search", "Smart search"),
                            ("semantic_search", "Semantic search"),
                            ("embedding", "Embedding"),
                            ("recommendation", "Recommendation"),
                            ("similar_products", "Similar products"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=30)),
                ("model_name", models.CharField(max_length=120)),
                ("prompt_template_version", models.CharField(blank=True, max_length=50)),
                ("prompt", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("fallback", "Fallback"),
                            ("cached", "Cached"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["feature", "-created_at"], name="ai_log_feature_idx"),
                    models.Index(
                        fields=["provider", "status", "-created_at"], name="ai_log_provider_idx"
                    ),
                    models.Index(fields=["user", "-created_at"], name="ai_log_user_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("estimated_cost__gte", 0)),
                        name="ai_log_cost_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("language_code", models.CharField(default="vi", max_length=10)),
                ("model_name", models.CharField(max_length=120)),
                ("model_version", models.CharField(blank=True, max_length=80)),
                (
                    "content_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Content hash must be a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("source_text", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="product.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-indexed_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["product", "model_name", "language_code"],
                        name="ai_embed_product_idx",
                    ),
                    models.Index(fields=["content_hash"], name="ai_embed_hash_idx"),
                    models.Index(fields=["-indexed_at"], name="ai_embed_indexed_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", True)),
                        fields=("product", "language_code", "model_name", "content_hash"),
                        name="ai_embed_product_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", False)),
                        fields=(
                            "product",
                            "variant",
                            "language_code",
                            "model_name",
                            "content_hash",
                        ),
                        name="ai_embed_variant_unique",
                    ),
                ],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_product_embedding_hnsw,
                    reverse_code=drop_product_embedding_hnsw,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="productembedding",
                    index=pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="ai_embed_vector_hnsw",
                        opclasses=("vector_cosine_ops",),
                    ),
                ),
            ],
        ),
    ]
