# Generated by Django 5.2.16 on 2026-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequestlog",
            name="feature",
            field=models.CharField(
                choices=[
                    ("smart_search", "Smart search"),
                    ("semantic_search", "Semantic search"),
                    ("embedding", "Embedding"),
                    ("recommendation", "Recommendation"),
                    ("similar_products", "Similar products"),
                    ("review_summary", "Review summary"),
                    ("product_summary", "Product summary"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
