# Generated by Django 5.2.16 on 2026-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_airequestlog_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='feature',
            field=models.CharField(choices=[('smart_search', 'Smart search'), ('semantic_search', 'Semantic search'), ('embedding', 'Embedding'), ('recommendation', 'Recommendation'), ('similar_products', 'Similar products'), ('review_summary', 'Review summary'), ('product_summary', 'Product summary'), ('product_compare', 'Product compare'), ('seller_listing', 'Seller listing generation'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
