# Generated by Django 5.2.16 on 2026-08-14 07:03

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


POLICY_DOCUMENTS = (
    (
        "shipping",
        "Phí giao hàng theo từng gian hàng",
        "Mercato tính phí giao hàng riêng cho từng gian hàng trong một lần checkout. "
        "Nếu gian hàng chưa cấu hình quy tắc phí riêng, hệ thống áp dụng phí giao hàng "
        "tiêu chuẩn 30.000 ₫ cho phần đơn hàng của gian hàng đó. Tổng phí được hiển thị "
        "trong bước xem trước checkout trước khi khách xác nhận đặt hàng.",
    ),
    (
        "shipping",
        "Phương thức và trạng thái giao hàng",
        "Luồng hiện tại hỗ trợ Giao hàng tiêu chuẩn cho từng phần đơn theo gian hàng. "
        "Mỗi phần đơn có trạng thái riêng: chờ xác nhận, đã xác nhận, đang đóng gói, "
        "đang giao, đã giao và hoàn thành. Mercato chưa công bố cam kết thời gian giao "
        "cố định; khách nên theo dõi trạng thái thực tế trong trang đơn hàng.",
    ),
    (
        "return",
        "Điều kiện và thời hạn yêu cầu trả hàng",
        "Khách chỉ có thể mở yêu cầu trả hàng khi phần đơn của gian hàng đã ở trạng "
        "thái Hoàn thành. Thời hạn mặc định là 7 ngày kể từ thời điểm hoàn thành và có "
        "thể được quản trị viên cấu hình. Yêu cầu phải nêu lý do, chọn đúng sản phẩm và "
        "số lượng cần trả; có thể đính kèm tối đa 6 tệp ảnh hoặc video làm chứng cứ.",
    ),
    (
        "return",
        "Xử lý hoàn tiền và khiếu nại",
        "Seller xem xét yêu cầu trả hàng và có thể đồng ý hoặc từ chối kèm phản hồi. "
        "Khi được đồng ý, số tiền yêu cầu hợp lệ được chuyển sang quy trình hoàn tiền. "
        "Nếu Seller từ chối, khách có thể chuyển yêu cầu thành khiếu nại để Admin xem "
        "chứng cứ và quyết định hoàn toàn bộ, hoàn một phần hoặc từ chối.",
    ),
    (
        "payment",
        "Phương thức thanh toán đang hỗ trợ",
        "Mercato hiện hỗ trợ Thanh toán khi nhận hàng (COD) và VNPay Sandbox. Đơn "
        "VNPay có 15 phút để hoàn tất thanh toán; kết quả callback đã xác minh từ VNPay "
        "là nguồn xác định trạng thái thanh toán. Với COD, tiền được ghi nhận khi phần "
        "đơn được xác nhận đã giao và đã thu tiền.",
    ),
)


def create_policy_document_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    policy_document = apps.get_model("ai", "PolicyDocument")
    table = schema_editor.quote_name(policy_document._meta.db_table)
    column = schema_editor.quote_name(policy_document._meta.get_field("embedding").column)
    index = schema_editor.quote_name("policy_doc_vector_hnsw")
    schema_editor.execute(
        f"CREATE INDEX IF NOT EXISTS {index} ON {table} "
        f"USING hnsw ({column} vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def drop_policy_document_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        index = schema_editor.quote_name("policy_doc_vector_hnsw")
        schema_editor.execute(f"DROP INDEX IF EXISTS {index}")


def seed_verified_policy_documents(apps, schema_editor):
    PolicyDocument = apps.get_model("ai", "PolicyDocument")
    for category, title, content in POLICY_DOCUMENTS:
        PolicyDocument.objects.update_or_create(
            category=category,
            title=title,
            defaults={"content": content, "is_active": True},
        )


def remove_seeded_policy_documents(apps, schema_editor):
    PolicyDocument = apps.get_model("ai", "PolicyDocument")
    titles = [title for _, title, _ in POLICY_DOCUMENTS]
    PolicyDocument.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_airequestlog_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='feature',
            field=models.CharField(choices=[('smart_search', 'Smart search'), ('semantic_search', 'Semantic search'), ('embedding', 'Embedding'), ('recommendation', 'Recommendation'), ('similar_products', 'Similar products'), ('review_summary', 'Review summary'), ('product_summary', 'Product summary'), ('product_compare', 'Product compare'), ('seller_listing', 'Seller listing generation'), ('chat_turn', 'Shopping assistant turn'), ('chat_summarize', 'Shopping assistant history summary'), ('policy_embedding', 'Policy embedding'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('closed', 'Đã đóng'), ('escalated', 'Đã chuyển CSKH')], db_index=True, default='active', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('history_summary', models.TextField(blank=True)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ('-last_active_at', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_token__isnull', False), _connector='OR'), name='chat_session_owner_required')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Khách'), ('assistant', 'Trợ lý'), ('tool', 'Kết quả công cụ')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='ai.airequestlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('shipping', 'Giao hàng'), ('return', 'Đổi trả'), ('payment', 'Thanh toán'), ('warranty', 'Bảo hành')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'policy_documents',
                'ordering': ('category', 'title', 'id'),
                'indexes': [models.Index(fields=['category', 'is_active'], name='policy_category_active_idx')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_policy_document_hnsw,
                    reverse_code=drop_policy_document_hnsw,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='policydocument',
                    index=pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=['embedding'],
                        m=16,
                        name='policy_doc_vector_hnsw',
                        opclasses=('vector_cosine_ops',),
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_msg_session_idx'),
        ),
        migrations.RunPython(
            seed_verified_policy_documents,
            reverse_code=remove_seeded_policy_documents,
        ),
    ]
