# Generated by Django 5.2 for the shopping assistant support workflow.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_alter_airequestlog_feature_chatsession_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="experiment_variant",
            field=models.CharField(db_index=True, default="control", max_length=40),
        ),
        migrations.CreateModel(
            name="ChatHandoff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("open", "Chờ tiếp nhận"), ("assigned", "Đã tiếp nhận"), ("resolved", "Đã xử lý"), ("closed", "Đã đóng")], db_index=True, default="open", max_length=20)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("conversation_summary", models.TextField(blank=True)),
                ("context_snapshot", models.JSONField(blank=True, default=list)),
                ("channel", models.CharField(default="web", max_length=30)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_chat_handoffs", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_handoffs", to=settings.AUTH_USER_MODEL)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="handoffs", to="ai.chatsession")),
            ],
            options={
                "db_table": "chat_handoffs",
                "ordering": ("-created_at", "-id"),
                "indexes": [models.Index(fields=["status", "-created_at"], name="chat_handoff_status_idx"), models.Index(fields=["session", "-created_at"], name="chat_handoff_session_idx")],
            },
        ),
        migrations.CreateModel(
            name="ChatFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("resolved", models.BooleanField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=1000)),
                ("message", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="ai.chatmessage")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedback_entries", to="ai.chatsession")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_feedback_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "chat_feedback",
                "ordering": ("-created_at", "-id"),
                "indexes": [models.Index(fields=["rating", "-created_at"], name="chat_feedback_rating_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(("rating__gte", 1), ("rating__lte", 5)), name="chat_feedback_rating_range")],
            },
        ),
    ]
