# Generated by Django 5.2.16 on 2026-07-27 04:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'is_deleted', 'name'], name='catalog_brand_public_idx'), models.Index(fields=['created_at'], name='catalog_brand_created_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_brand_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ('sort_order', 'name', 'id'),
                'indexes': [models.Index(fields=['parent', 'sort_order'], name='catalog_cat_parent_sort_idx'), models.Index(fields=['is_active', 'is_deleted', 'sort_order'], name='catalog_cat_public_idx'), models.Index(fields=['created_at'], name='catalog_cat_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='catalog_category_not_self_parent')],
            },
        ),
    ]
